UPDATE TB_COTACAO_HISTORICA, TB_ALTERACAO_COTAS
SET TB_COTACAO_HISTORICA.PRECO_ABER = ROUND(PRECO_ABER / COALESCE(TB_ALTERACAO_COTAS.MULTIPLO, 1), 2)
, TB_COTACAO_HISTORICA.PRECO_MAX = ROUND(PRECO_MAX / COALESCE(TB_ALTERACAO_COTAS.MULTIPLO, 1), 2)
, TB_COTACAO_HISTORICA.PRECO_MIN = ROUND(PRECO_MIN/ COALESCE(TB_ALTERACAO_COTAS.MULTIPLO, 1), 2)
, TB_COTACAO_HISTORICA.PRECO_MED = ROUND(PRECO_MED/ COALESCE(TB_ALTERACAO_COTAS.MULTIPLO, 1), 2)
, TB_COTACAO_HISTORICA.PRECO_ULT = ROUND(PRECO_ULT / COALESCE(TB_ALTERACAO_COTAS.MULTIPLO, 1), 2)
, TB_COTACAO_HISTORICA.PRECO_OFER_COMPRA = ROUND(PRECO_OFER_COMPRA / COALESCE(TB_ALTERACAO_COTAS.MULTIPLO, 1), 2)
, TB_COTACAO_HISTORICA.PRECO_OFER_VENDA = ROUND(PRECO_OFER_VENDA / COALESCE(TB_ALTERACAO_COTAS.MULTIPLO, 1), 2)
, TB_COTACAO_HISTORICA.COD_PAPEL = IF(TB_ALTERACAO_COTAS.TIPO=4, TB_ALTERACAO_COTAS.NOVO_COD_PAPEL, TB_COTACAO_HISTORICA.COD_PAPEL)
WHERE TB_ALTERACAO_COTAS.COD_PAPEL = TB_COTACAO_HISTORICA.COD_PAPEL 
AND TB_COTACAO_HISTORICA.DATA_PREGAO < TB_ALTERACAO_COTAS.DATA_INICIAL
and  TB_ALTERACAO_COTAS.ID>=4;