SET GLOBAL storage_engine = MyISAM;

CREATE DATABASE IF NOT EXISTS FINANCAS;

USE FINANCAS;

CREATE TABLE IF NOT EXISTS DIM_ACAO_FAVORITOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
COD_PAPEL VARCHAR(100) UNIQUE,
INDEX (COD_PAPEL)
)
ENGINE = MYISAM;

CREATE TABLE IF NOT EXISTS tb_cotacao_historica (
  ID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TIP_REG int(11),
  PERIODO date,
  DATA_PREGAO date,
  COD_BDI int(11),
  COD_PAPEL varchar(12),
  TP_MERC int(11),
  NOM_RES varchar(12),
  ESP_PAPEL varchar(10),
  PRAZO_TERMO varchar(3),
  MOD_REF varchar(4),
  PRECO_ABER float,
  PRECO_MAX float,
  PRECO_MIN float,
  PRECO_MED float,
  PRECO_ULT float,
  PRECO_OFER_COMPRA float,
  PRECO_OFER_VENDA float,
  PRECO_FECH_ANTERIOR float,
  PRECO_FECH_SEM_ANTERIOR float,
  PRECO_FECH_MES_ANTERIOR float,
  PRECO_INI_ANO float,
PRECO_FECH_ANTERIOR_MEDIO FLOAT,
PRECO_FECH_SEM_ANTERIOR_MEDIO FLOAT,
PRECO_FECH_MES_ANTERIOR_MEDIO FLOAT,
PRECO_INI_ANO_MEDIO FLOAT,
  TOT_NEG int(11),
  QTD_TOTAL int(11),
  VOL_TOTAL float,
  PRECO_EXERC float,
  IND_PRECOS int(11),
  DATA_VENC date,
  FAT_COTACAO int(11),
  PRECO_PONTOS1 float,
  PRECO_PONTOS float,
  COD_ISIN varchar(12),
  DISMES varchar(3),
  FL_PROCESSADO int default 0,
INDEX COD_BDI (COD_BDI),
INDEX DATA_PREGAO (DATA_PREGAO)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS TMP_COTACAO_HISTORICA;

CREATE TABLE IF NOT EXISTS TMP_COTACAO_HISTORICA(
TIP_REG INT,
PERIODO DATE,
DATA_PREGAO DATE,
COD_BDI INT,
COD_PAPEL VARCHAR(12),
TP_MERC INT,
NOM_RES VARCHAR(12),
ESP_PAPEL VARCHAR(10),
PRAZO_TERMO VARCHAR(3),
MOD_REF VARCHAR(4),
PRECO_ABER FLOAT,
PRECO_MAX FLOAT,
PRECO_MIN FLOAT,
PRECO_MED FLOAT,
PRECO_ULT FLOAT,
PRECO_OFER_COMPRA FLOAT,
PRECO_OFER_VENDA FLOAT,
PRECO_FECH_ANTERIOR FLOAT,
PRECO_FECH_SEM_ANTERIOR FLOAT,
PRECO_FECH_MES_ANTERIOR FLOAT,
PRECO_INI_ANO FLOAT,
PRECO_FECH_ANTERIOR_MEDIO FLOAT,
PRECO_FECH_SEM_ANTERIOR_MEDIO FLOAT,
PRECO_FECH_MES_ANTERIOR_MEDIO FLOAT,
PRECO_INI_ANO_MEDIO FLOAT,
TOT_NEG INT,
QTD_TOTAL INT,
VOL_TOTAL FLOAT,
PRECO_EXERC FLOAT,
IND_PRECOS INT,
DATA_VENC DATE,
FAT_COTACAO INT,
PRECO_PONTOS1 FLOAT,
PRECO_PONTOS FLOAT,
COD_ISIN VARCHAR(12),
DISMES VARCHAR(3),
FL_PROCESSADO int default 0,
INDEX COD_PAPEL(COD_PAPEL),
INDEX DATA_PREGAO(DATA_PREGAO)
)
ENGINE = MYISAM;



LOAD DATA INFILE '/sdcard/www/public/cargas/txt/COTAHIST.TXT'
INTO TABLE TMP_COTACAO_HISTORICA
CHARACTER SET 'utf8'
IGNORE 1 LINES
(@row)
SET
TIP_REG = TRIM(SUBSTR(@row,1,2)),
DATA_PREGAO = STR_TO_DATE(TRIM(SUBSTR(@row,3,8)), "%Y%m%d"),
COD_BDI = TRIM(SUBSTR(@row,11,2)),
COD_PAPEL = TRIM(SUBSTR(@row,13,12)),
TP_MERC = TRIM(SUBSTR(@row,25,3)),
NOM_RES = TRIM(SUBSTR(@row,28,12)),
ESP_PAPEL = TRIM(SUBSTR(@row,40,10)),
PRAZO_TERMO = COALESCE(TRIM(SUBSTR(@row,50,3)),'000'),
MOD_REF = TRIM(SUBSTR(@row,53,4)),
PRECO_ABER = CAST(TRIM(SUBSTR(@row,57,13)) AS SIGNED)/100,
PRECO_MAX = CAST(TRIM(SUBSTR(@row,70,13)) AS SIGNED)/100,
PRECO_MIN = CAST(TRIM(SUBSTR(@row,83,13)) AS SIGNED)/100,
PRECO_MED = CAST(TRIM(SUBSTR(@row,96,13)) AS SIGNED)/100,
PRECO_ULT = CAST(TRIM(SUBSTR(@row,109,13)) AS SIGNED)/100,
PRECO_OFER_COMPRA = CAST(TRIM(SUBSTR(@row,122,13)) AS SIGNED)/100,
PRECO_OFER_VENDA = CAST(TRIM(SUBSTR(@row,135,13)) AS SIGNED)/100,
TOT_NEG = TRIM(SUBSTR(@row,148,5)),
QTD_TOTAL = TRIM(SUBSTR(@row,153,18)),
VOL_TOTAL = CAST(TRIM(SUBSTR(@row,171,18)) AS SIGNED)/100,
PRECO_EXERC = CAST(TRIM(SUBSTR(@row,189,13)) AS SIGNED)/100,
IND_PRECOS = TRIM(SUBSTR(@row,202,1)),
DATA_VENC = STR_TO_DATE(TRIM(SUBSTR(@row,203,8)), "%Y%m%d"),
FAT_COTACAO = TRIM(SUBSTR(@row,211,7)),
PRECO_PONTOS = CAST(TRIM(SUBSTR(@row,218,13)) AS UNSIGNED)/1000000000,
COD_ISIN = TRIM(SUBSTR(@row,231,12)),
DISMES = TRIM(SUBSTR(@row,243,3)),
PERIODO = STR_TO_DATE(concat(TRIM(SUBSTR(@row,3,6)),"01"), "%Y%m%d"),
PRECO_PONTOS1 = TRIM(SUBSTR(@row,218,13));

UPDATE TMP_COTACAO_HISTORICA, TB_ALTERACAO_COTAS
SET TMP_COTACAO_HISTORICA.PRECO_ABER = ROUND(PRECO_ABER / COALESCE(TB_ALTERACAO_COTAS.MULTIPLO, 1), 2)
, TMP_COTACAO_HISTORICA.PRECO_MAX = ROUND(PRECO_MAX / COALESCE(TB_ALTERACAO_COTAS.MULTIPLO, 1), 2)
, TMP_COTACAO_HISTORICA.PRECO_MIN = ROUND(PRECO_MIN/ COALESCE(TB_ALTERACAO_COTAS.MULTIPLO, 1), 2)
, TMP_COTACAO_HISTORICA.PRECO_MED = ROUND(PRECO_MED/ COALESCE(TB_ALTERACAO_COTAS.MULTIPLO, 1), 2)
, TMP_COTACAO_HISTORICA.PRECO_ULT = ROUND(PRECO_ULT / COALESCE(TB_ALTERACAO_COTAS.MULTIPLO, 1), 2)
, TMP_COTACAO_HISTORICA.PRECO_OFER_COMPRA = ROUND(PRECO_OFER_COMPRA / COALESCE(TB_ALTERACAO_COTAS.MULTIPLO, 1), 2)
, TMP_COTACAO_HISTORICA.PRECO_OFER_VENDA = ROUND(PRECO_OFER_VENDA / COALESCE(TB_ALTERACAO_COTAS.MULTIPLO, 1), 2)
, TMP_COTACAO_HISTORICA.COD_PAPEL = IF(TB_ALTERACAO_COTAS.TIPO=4, TB_ALTERACAO_COTAS.NOVO_COD_PAPEL, TMP_COTACAO_HISTORICA.COD_PAPEL)
WHERE TB_ALTERACAO_COTAS.COD_PAPEL = TMP_COTACAO_HISTORICA.COD_PAPEL
AND TMP_COTACAO_HISTORICA.DATA_PREGAO < TB_ALTERACAO_COTAS.DATA_INICIAL;

DELETE FROM TMP_COTACAO_HISTORICA WHERE TIP_REG IN(0, 99);

DROP TABLE IF EXISTS TB_DATA_CORTE;

CREATE TABLE IF NOT EXISTS TB_DATA_CORTE AS
SELECT Min(TMP_COTACAO_HISTORICA.DATA_PREGAO) AS CORTE_INICIAL, Max(TMP_COTACAO_HISTORICA.DATA_PREGAO) AS CORTE_FINAL
FROM TMP_COTACAO_HISTORICA;

DELETE
FROM TB_COTACAO_HISTORICA
WHERE DATA_PREGAO Between (SELECT CORTE_INICIAL FROM TB_DATA_CORTE) And (SELECT CORTE_FINAL FROM TB_DATA_CORTE);

INSERT INTO TB_COTACAO_HISTORICA
SELECT NULL, TMP_COTACAO_HISTORICA.*
FROM TMP_COTACAO_HISTORICA;