SET GLOBAL storage_engine = MyISAM;

CREATE DATABASE IF NOT EXISTS FINANCAS;

USE FINANCAS;

CREATE TABLE IF NOT EXISTS DIM_ACAO_FAVORITOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
COD_PAPEL VARCHAR(100) UNIQUE,
INDEX (COD_PAPEL)
)
ENGINE = MYISAM;

CREATE TABLE IF NOT EXISTS TB_COTACAO_HISTORICA(
ID INT AUTO_INCREMENT PRIMARY KEY,
TIP_REG INT,
PERIODO DATE,
DATA_PREGAO DATE,
COD_BDI INT,
COD_PAPEL VARCHAR(12),
TP_MERC INT,
NOM_RES VARCHAR(12),
ESP_PAPEL VARCHAR(10),
PRAZO_TERMO VARCHAR(3),
MOD_REF VARCHAR(4),
PRECO_ABER FLOAT,
PRECO_MAX FLOAT,
PRECO_MIN FLOAT,
PRECO_MED FLOAT,
PRECO_ULT FLOAT,
PRECO_OFER_COMPRA FLOAT,
PRECO_OFER_VENDA FLOAT,
PRECO_FECH_ANTERIOR FLOAT,
PRECO_FECH_MES_ANTERIOR FLOAT,
PRECO_INI_ANO FLOAT,
TOT_NEG INT,
QTD_TOTAL INT,
VOL_TOTAL FLOAT,
PRECO_EXERC FLOAT,
IND_PRECOS INT,
DATA_VENC DATE,
FAT_COTACAO INT,
PRECO_PONTOS1 FLOAT,
PRECO_PONTOS FLOAT,
COD_ISIN VARCHAR(12),
DISMES VARCHAR(3),
INDEX COD_BDI(COD_BDI),
INDEX DATA_PREGAO(DATA_PREGAO)
) ENGINE = MYISAM;

DROP TABLE IF EXISTS TMP_COTACAO_HISTORICA;
CREATE TABLE IF NOT EXISTS TMP_COTACAO_HISTORICA(
TIP_REG INT,
PERIODO DATE,
DATA_PREGAO DATE,
COD_BDI INT,
COD_PAPEL VARCHAR(12),
TP_MERC INT,
NOM_RES VARCHAR(12),
ESP_PAPEL VARCHAR(10),
PRAZO_TERMO VARCHAR(3),
MOD_REF VARCHAR(4),
PRECO_ABER FLOAT,
PRECO_MAX FLOAT,
PRECO_MIN FLOAT,
PRECO_MED FLOAT,
PRECO_ULT FLOAT,
PRECO_OFER_COMPRA FLOAT,
PRECO_OFER_VENDA FLOAT,
PRECO_FECH_ANTERIOR FLOAT,
PRECO_FECH_MES_ANTERIOR FLOAT,
PRECO_INI_ANO FLOAT,
TOT_NEG INT,
QTD_TOTAL INT,
VOL_TOTAL FLOAT,
PRECO_EXERC FLOAT,
IND_PRECOS INT,
DATA_VENC DATE,
FAT_COTACAO INT,
PRECO_PONTOS1 FLOAT,
PRECO_PONTOS FLOAT,
COD_ISIN VARCHAR(12),
DISMES VARCHAR(3))
ENGINE = MYISAM;

LOAD DATA INFILE '/sdcard/www/public/cargas/txt/COTAHIST.TXT' 
INTO TABLE TMP_COTACAO_HISTORICA 
CHARACTER SET 'utf8'
IGNORE 1 LINES
(@row)
SET 
TIP_REG = TRIM(SUBSTR(@row,1,2)),
DATA_PREGAO = STR_TO_DATE(TRIM(SUBSTR(@row,3,8)), "%Y%m%d"),
COD_BDI = TRIM(SUBSTR(@row,11,2)),
COD_PAPEL = TRIM(SUBSTR(@row,13,12)),
TP_MERC = TRIM(SUBSTR(@row,25,3)),
NOM_RES = TRIM(SUBSTR(@row,28,12)),
ESP_PAPEL = TRIM(SUBSTR(@row,40,10)),
PRAZO_TERMO = COALESCE(TRIM(SUBSTR(@row,50,3)),'000'),
MOD_REF = TRIM(SUBSTR(@row,53,4)),
PRECO_ABER = CAST(TRIM(SUBSTR(@row,57,13)) AS SIGNED)/100,
PRECO_MAX = CAST(TRIM(SUBSTR(@row,70,13)) AS SIGNED)/100,
PRECO_MIN = CAST(TRIM(SUBSTR(@row,83,13)) AS SIGNED)/100,
PRECO_MED = CAST(TRIM(SUBSTR(@row,96,13)) AS SIGNED)/100,
PRECO_ULT = CAST(TRIM(SUBSTR(@row,109,13)) AS SIGNED)/100,
PRECO_OFER_COMPRA = CAST(TRIM(SUBSTR(@row,122,13)) AS SIGNED)/100,
PRECO_OFER_VENDA = CAST(TRIM(SUBSTR(@row,135,13)) AS SIGNED)/100,
TOT_NEG = TRIM(SUBSTR(@row,148,5)),
QTD_TOTAL = TRIM(SUBSTR(@row,153,18)),
VOL_TOTAL = CAST(TRIM(SUBSTR(@row,171,18)) AS SIGNED)/100,
PRECO_EXERC = CAST(TRIM(SUBSTR(@row,189,13)) AS SIGNED)/100,
IND_PRECOS = TRIM(SUBSTR(@row,202,1)),
DATA_VENC = STR_TO_DATE(TRIM(SUBSTR(@row,203,8)), "%Y%m%d"),
FAT_COTACAO = TRIM(SUBSTR(@row,211,7)),
PRECO_PONTOS = CAST(TRIM(SUBSTR(@row,218,13)) AS UNSIGNED)/1000000000,
COD_ISIN = TRIM(SUBSTR(@row,231,12)),
DISMES = TRIM(SUBSTR(@row,243,3)),
PERIODO = STR_TO_DATE(concat(TRIM(SUBSTR(@row,3,6)),"01"), "%Y%m%d"),
PRECO_FECH_ANTERIOR = 0,
PRECO_PONTOS1 = TRIM(SUBSTR(@row,218,13));

DELETE FROM TMP_COTACAO_HISTORICA WHERE TIP_REG IN(0, 99);

DROP TABLE IF EXISTS TB_DATA_CORTE;

CREATE TABLE IF NOT EXISTS TB_DATA_CORTE AS
SELECT Min(TMP_COTACAO_HISTORICA.DATA_PREGAO) AS CORTE_INICIAL, Max(TMP_COTACAO_HISTORICA.DATA_PREGAO) AS CORTE_FINAL
FROM TMP_COTACAO_HISTORICA;

DELETE 
FROM TB_COTACAO_HISTORICA
WHERE DATA_PREGAO Between (SELECT CORTE_INICIAL FROM TB_DATA_CORTE) And (SELECT CORTE_FINAL FROM TB_DATA_CORTE);

INSERT INTO TB_COTACAO_HISTORICA
SELECT NULL, TMP_COTACAO_HISTORICA.*
FROM TMP_COTACAO_HISTORICA;

DROP TABLE IF EXISTS TB_MAPA_DATA;

CREATE TABLE IF NOT EXISTS TB_MAPA_DATA AS
SELECT DISTINCT PERIODO, DATA_PREGAO 
FROM TB_COTACAO_HISTORICA
ORDER BY DATA_PREGAO;

ALTER TABLE TB_MAPA_DATA ADD KEY DATA_PREGAO(DATA_PREGAO) ;
ALTER TABLE TB_MAPA_DATA ADD COLUMN ID INT AUTO_INCREMENT PRIMARY KEY FIRST;

CREATE OR REPLACE VIEW VW_ULTIMO_FOTO AS
SELECT MAX(DATA_PREGAO) AS ULTM_FOTO_PRGO
FROM TB_MAPA_DATA;

CREATE OR REPLACE VIEW VW_MAPA_DATA AS 
SELECT DISTINCT PERIODO, DATA_PREGAO, ID, ID-1 AS ID_ANTERIOR
FROM TB_MAPA_DATA;

CREATE OR REPLACE VIEW AUX_CORTE_MES AS
SELECT PERIODO
, DATE_ADD(PERIODO, INTERVAL 1 MONTH) AS PROX_PERIODO
, Min(VW_MAPA_DATA.DATA_PREGAO) AS PRI_PREGAO_MES
, Max(VW_MAPA_DATA.DATA_PREGAO) AS ULT_PREGAO_MES
FROM VW_MAPA_DATA
GROUP BY 1, 2;

CREATE OR REPLACE VIEW AUX_CORTE_MES_FINAL AS
SELECT AUX_CORTE_MES.PERIODO
, IF(AUX_CORTE_MES_1.ULT_PREGAO_MES Is Null,AUX_CORTE_MES.PRI_PREGAO_MES,AUX_CORTE_MES_1.ULT_PREGAO_MES) AS CORTE_MES
FROM AUX_CORTE_MES 
LEFT JOIN AUX_CORTE_MES AS AUX_CORTE_MES_1 ON AUX_CORTE_MES.PERIODO = AUX_CORTE_MES_1.PROX_PERIODO;

CREATE OR REPLACE VIEW VW_PREGAO_ANTERIOR AS 
SELECT VW_MAPA_DATA.PERIODO
, VW_MAPA_DATA.DATA_PREGAO
, TB_MAPA_DATA.DATA_PREGAO AS DATA_PREGAO_ANT
, AUX_CORTE_MES_FINAL.CORTE_MES
FROM VW_MAPA_DATA 
INNER JOIN TB_MAPA_DATA ON TB_MAPA_DATA.ID = VW_MAPA_DATA.ID_ANTERIOR
LEFT JOIN AUX_CORTE_MES_FINAL ON VW_MAPA_DATA.PERIODO = AUX_CORTE_MES_FINAL.PERIODO;

DROP TABLE IF EXISTS TB_PRECO_ANTERIOR;

CREATE TABLE IF NOT EXISTS TB_PRECO_ANTERIOR AS
SELECT VW_PREGAO_ANTERIOR.DATA_PREGAO
, VW_PREGAO_ANTERIOR.DATA_PREGAO_ANT
, TB_COTACAO_HISTORICA.COD_BDI
, TB_COTACAO_HISTORICA.COD_PAPEL
, TB_COTACAO_HISTORICA.PRAZO_TERMO
, TB_COTACAO_HISTORICA.PRECO_ULT
FROM TB_COTACAO_HISTORICA 
INNER JOIN VW_PREGAO_ANTERIOR ON TB_COTACAO_HISTORICA.DATA_PREGAO = VW_PREGAO_ANTERIOR.DATA_PREGAO_ANT;

ALTER TABLE TB_PRECO_ANTERIOR ADD INDEX PRECO_ANT(PRAZO_TERMO, COD_PAPEL, COD_BDI, DATA_PREGAO);

DROP TABLE IF EXISTS TB_PRECO_MES_ANT;

CREATE TABLE IF NOT EXISTS TB_PRECO_MES_ANT AS
SELECT DISTINCT AUX_CORTE_MES_FINAL.PERIODO
, AUX_CORTE_MES_FINAL.CORTE_MES
, TB_COTACAO_HISTORICA.COD_BDI
, TB_COTACAO_HISTORICA.COD_PAPEL
, TB_COTACAO_HISTORICA.PRAZO_TERMO
, TB_COTACAO_HISTORICA.PRECO_ULT
FROM TB_COTACAO_HISTORICA 
INNER JOIN AUX_CORTE_MES_FINAL ON TB_COTACAO_HISTORICA.DATA_PREGAO = AUX_CORTE_MES_FINAL.CORTE_MES;

ALTER TABLE TB_PRECO_MES_ANT ADD INDEX PRECO_ANT(PRAZO_TERMO, COD_PAPEL, COD_BDI, PERIODO);

DROP TABLE IF EXISTS TB_PRECO_INI_ANO;

CREATE TABLE IF NOT EXISTS TB_PRECO_INI_ANO AS
SELECT DISTINCT TB_COTACAO_HISTORICA.COD_BDI
, TB_COTACAO_HISTORICA.COD_PAPEL
, TB_COTACAO_HISTORICA.PRAZO_TERMO
, TB_COTACAO_HISTORICA.PRECO_ABER
FROM TB_COTACAO_HISTORICA 
WHERE TB_COTACAO_HISTORICA.DATA_PREGAO = '2019-01-02';

ALTER TABLE TB_PRECO_INI_ANO ADD INDEX PRECO_INI_ANO(PRAZO_TERMO, COD_PAPEL, COD_BDI);


UPDATE TB_COTACAO_HISTORICA a,  TB_PRECO_ANTERIOR b
 SET a.PRECO_FECH_ANTERIOR = b.PRECO_ULT
WHERE  a.PRAZO_TERMO = b.PRAZO_TERMO
AND a.COD_PAPEL = b.COD_PAPEL
AND a.COD_BDI = b.COD_BDI
AND a.DATA_PREGAO = b.DATA_PREGAO;


UPDATE TB_COTACAO_HISTORICA a,  TB_PRECO_MES_ANT b
 SET a.PRECO_FECH_MES_ANTERIOR = b.PRECO_ULT
WHERE  a.PRAZO_TERMO = b.PRAZO_TERMO
AND a.COD_PAPEL = b.COD_PAPEL
AND a.COD_BDI = b.COD_BDI
AND a.PERIODO = b.PERIODO;

UPDATE TB_COTACAO_HISTORICA a,  TB_PRECO_INI_ANO b
 SET a.PRECO_INI_ANO = b.PRECO_ABER
WHERE  a.PRAZO_TERMO = b.PRAZO_TERMO
AND a.COD_PAPEL = b.COD_PAPEL
AND a.COD_BDI = b.COD_BDI;

CREATE TABLE IF NOT EXISTS TB_BDI(
COD_BDI INT PRIMARY KEY,
DESC_BDI VARCHAR(100))
ENGINE = MYISAM;

TRUNCATE TABLE TB_BDI;

LOAD DATA INFILE '/sdcard/www/public/cargas/txt/TB_BDI.txt' 
INTO TABLE  TB_BDI
CHARACTER SET 'utf8'
IGNORE 1 LINES
(COD_BDI, DESC_BDI);

CREATE TABLE IF NOT EXISTS DIM_SETOR_ECONOMICO(
ID INT AUTO_INCREMENT PRIMARY KEY,
SETOR_ECONOMICO VARCHAR(100),
SUBSETOR VARCHAR(100),
SEGMENTO VARCHAR(100),
EMPRESA VARCHAR(100),
CODIGO VARCHAR(100),
COD_SEGMENTO VARCHAR(100)
)
ENGINE = MYISAM;

TRUNCATE TABLE DIM_SETOR_ECONOMICO;
LOAD DATA INFILE '/sdcard/www/public/cargas/txt/DIM_SETOR_ECONOMICO.txt' 
INTO TABLE DIM_SETOR_ECONOMICO 
CHARACTER SET 'utf8'
IGNORE 1 LINES
(SETOR_ECONOMICO, SUBSETOR, SEGMENTO, EMPRESA, CODIGO, COD_SEGMENTO);

CREATE OR REPLACE VIEW VW_HIST_COTACAO as 
SELECT TB_COTACAO_HISTORICA.DATA_PREGAO
, Left(cod_papel,4) AS COD_EMPR
, TB_COTACAO_HISTORICA.COD_PAPEL
, TB_COTACAO_HISTORICA.NOM_RES
, TB_COTACAO_HISTORICA.PRECO_FECH_ANTERIOR
, TB_COTACAO_HISTORICA.PRECO_FECH_MES_ANTERIOR
, TB_COTACAO_HISTORICA.PRECO_ULT
, ROUND(If(TB_COTACAO_HISTORICA.PRECO_FECH_ANTERIOR=0,0,(PRECO_ULT/TB_COTACAO_HISTORICA.PRECO_FECH_ANTERIOR)-1)*100,2) AS VAR_DIA
, ROUND(If(TB_COTACAO_HISTORICA.PRECO_FECH_MES_ANTERIOR=0,0,(PRECO_ULT/TB_COTACAO_HISTORICA.PRECO_FECH_MES_ANTERIOR)-1)*100,2) AS VAR_MES
, ROUND(If(TB_COTACAO_HISTORICA.PRECO_INI_ANO=0,0,(PRECO_ULT/TB_COTACAO_HISTORICA.PRECO_INI_ANO)-1)*100,2) AS VAR_ANO
, TB_COTACAO_HISTORICA.QTD_TOTAL
FROM  TB_COTACAO_HISTORICA  AS TB_COTACAO_HISTORICA 
INNER JOIN TB_BDI ON TB_COTACAO_HISTORICA.COD_BDI = TB_BDI.COD_BDI
WHERE TB_BDI.COD_BDI=2;

CREATE OR REPLACE VIEW VW_MAIS_NEGOCIADAS_ULTM_PRGO as 
SELECT TB_COTACAO_HISTORICA.DATA_PREGAO
, Left(cod_papel,4) AS COD_EMPR
, TB_COTACAO_HISTORICA.COD_PAPEL
, TB_COTACAO_HISTORICA.NOM_RES
, TB_COTACAO_HISTORICA.PRECO_FECH_ANTERIOR
, TB_COTACAO_HISTORICA.PRECO_FECH_MES_ANTERIOR
, TB_COTACAO_HISTORICA.PRECO_ULT
, ROUND(If(TB_COTACAO_HISTORICA.PRECO_FECH_ANTERIOR=0,0,(PRECO_ULT/TB_COTACAO_HISTORICA.PRECO_FECH_ANTERIOR)-1)*100,2) AS VAR_DIA
, ROUND(If(TB_COTACAO_HISTORICA.PRECO_FECH_MES_ANTERIOR=0,0,(PRECO_ULT/TB_COTACAO_HISTORICA.PRECO_FECH_MES_ANTERIOR)-1)*100,2) AS VAR_MES
, ROUND(If(TB_COTACAO_HISTORICA.PRECO_INI_ANO=0,0,(PRECO_ULT/TB_COTACAO_HISTORICA.PRECO_INI_ANO)-1)*100,2) AS VAR_ANO
, TB_COTACAO_HISTORICA.QTD_TOTAL
FROM  TB_COTACAO_HISTORICA  AS TB_COTACAO_HISTORICA 
INNER JOIN TB_BDI ON TB_COTACAO_HISTORICA.COD_BDI = TB_BDI.COD_BDI
WHERE TB_COTACAO_HISTORICA.DATA_PREGAO= (SELECT ULTM_FOTO_PRGO FROM VW_ULTIMO_FOTO)
AND TB_BDI.COD_BDI=2
ORDER BY TB_COTACAO_HISTORICA.QTD_TOTAL DESC;

CREATE OR REPLACE VIEW VW_MAIS_NEGOCIADAS_ULTM_PRGO_SETOR as 
SELECT DIM_SETOR_ECONOMICO.SETOR_ECONOMICO
, DIM_SETOR_ECONOMICO.SUBSETOR
, DIM_SETOR_ECONOMICO.SEGMENTO
,VW_MAIS_NEGOCIADAS_ULTM_PRGO.*
,CASE WHEN FAV.COD_PAPEL IS NULL THEN 0 ELSE 1 END AS FL_FAVORITO
FROM VW_MAIS_NEGOCIADAS_ULTM_PRGO
LEFT JOIN DIM_ACAO_FAVORITOS FAV ON VW_MAIS_NEGOCIADAS_ULTM_PRGO.COD_PAPEL = FAV.COD_PAPEL
LEFT JOIN DIM_SETOR_ECONOMICO ON VW_MAIS_NEGOCIADAS_ULTM_PRGO.COD_EMPR = DIM_SETOR_ECONOMICO.CODIGO
ORDER BY VW_MAIS_NEGOCIADAS_ULTM_PRGO.VAR_MES, SETOR_ECONOMICO, SUBSETOR, SEGMENTO ;